import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import { courseLink, workshopLink } from './links';

const sidebars: SidebarsConfig = {
  instructions: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'category',
      collapsed: false,
      label: '🎁 Gifts',
      items: [
        {
          type: 'link',
          label: '👨🏻‍🏫 3-Day Workshop (30% off)',
          href: workshopLink,
        },
        {
          type: 'link',
          label: '📺 Video Course (60% off)',
          href: courseLink,
        },
      ],
    },
  ],
};

export default sidebars;
