import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  instructions: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'category',
      collapsed: false,
      label: '🎁 Gifts',
      items: [
        {
          type: 'link',
          label: '👨🏻‍🏫 3-Day Workshop (30% off)',
          href: 'https://luma.com/27f85isx?coupon=NGDE_KITCHEN_SPECIAL',
        },
        {
          type: 'link',
          label: '📺 Video Course (60% off)',
          href: 'https://courses.marmicode.io/courses/pragmatic-angular-testing?utm_source=angular-vitest-mini-workshop&utm_medium=sidenav&coupon=NGDE_KITCHEN_SPECIAL',
        },
      ],
    },
  ],
};

export default sidebars;
